// Invalid params
export const EmailIsRequired = 'Invalid params: Email is required'
export const FirstNameIsRequired = 'Invalid params: First name is required'
export const LastNameIsRequired = 'Invalid params: Last name is required'
export const InvalidUsernamePassword = 'Invalid username or password'
export const UserIdIsRequired = 'Invalid params: UserId is required'
export const AmountIsRequired = 'Invalid params: Amount is required'
export const FrequencyIsRequired = 'Invalid params: Frequency is required'
export const DonationIdIsRequired = 'Invalid params: Donation id is required'
export const PaymentIdIsRequired = 'Invalid params: Payment id is required'
export const PayoutIdIsRequired = 'Invalid params: Payout id is required'
export const TeacherIdIsRequired = 'Invalid params: Teacher id is required'
export const DescriptionIsRequired = 'Invalid params: Description is required'
export const LocationIsRequired = 'Invalid params: Location is required'
